In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
import sys
sys.path.append('../../scripts')
import json_parser # type: ignore

pd.set_option('display.max_columns', None)

In [2]:
json_file = '../../data/raw/AN2023.json' 

df = pd.read_json(json_file)
df = json_parser.flatten_data(json_file)

print(df.shape) # Rows, Columns

(10869, 83)

In [10]:
df.head()

,epglnren,epglren,co2,ephnd,software_utilizzato,ephndlim,epglnrenrs,sup_riscaldata,sup_raffrescata,vol_riscaldato,vol_raffrescato,sup_disperdente,rapsv,asolsut,data_sopralluogo,inizio_validita,fine_validita,classe_energetica,presenza_clim_invernale,presenza_clim_estiva,presenza_vent_meccanica,presenza_produzione_acs,presenza_illuminazione,presenza_trasporto_pc,yie,nzeb,motivazione,informazioni_miglioramento,inverno,estate,classe_energetica_raggiungibile,epglnren_raggiungibile,altra_motivazione,energiaesportata,vetenergiaesportata,informazioni_aggiuntive,anno_costruzione,piano,provincia,comune,gradi_giorno,codice_istat_comune,zona_climatica,dpr412,destinazione_uso,oggetto_attestato,numero_unita,tipologia_edilizia,tipologia_costruttiva,proprieta_edificio,cap,servizio_0_efficienza,servizio_0_epnren,servizio_0_epren,servizio_0_simulato,servizio_1_efficienza,servizio_1_epnren,servizio_1_epren,servizio_1_simulato,servizio_2_efficienza,servizio_2_epnren,servizio_2_epren,servizio_2_simulato,servizio_3_efficienza,servizio_3_epnren,servizio_3_epren,servizio_3_simulato,servizio_4_efficienza,servizio_4_epnren,servizio_4_epren,servizio_4_simulato,servizio_5_efficienza,servizio_5_epnren,servizio_5_epren,servizio_5_simulato,servizio_6_efficienza,servizio_6_epnren,servizio_6_epren,servizio_6_simulato,servizio_7_efficienza,servizio_7_epnren,servizio_7_epren,servizio_7_simulato
0,153.92,0.00,28.86,89.08,Namirial Termo 6,12.233700,49.060000,53.41,0.00,179.54,0.00,34.83,0.1940,0.0125,2023-09-11,2023-09-21,2033-09-21,F,True,False,False,True,False,False,0.6025,False,1,Data sopralluogo: 11/09/2023,2,1,E,120.10,NaN,0.0,0,L'unità immobiliare non è dotata di un impiant...,1700,Secondo,Ancona,Jesi,1899,042021,D,0,0,1,12,3,0,0,60035,0.73,121.56,0.00,1.0,NaN,NaN,NaN,NaN,0.57,32.36,0.00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,196.28,0.00,40.42,150.51,TERMOLOG EpiX,34.605655,68.612614,210.07,0.00,865.20,0.00,540.37,0.6246,0.0503,2023-09-13,2023-09-21,2033-09-21,F,True,False,False,True,False,False,0.1794,False,1,i miglioramenti energetici si trovano nell`app...,2,2,B,77.96,NaN,0.0,0,NaN,1955,T-1-2,AN,Falconara Marittima,1888,042018,D,0,0,1,1,0,0,0,60015,0.83,181.88,0.00,0.0,NaN,NaN,NaN,NaN,0.84,14.40,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,193.17,9.82,39.06,88.74,Namirial Termo 6,21.663000,92.540000,72.29,72.29,261.13,261.13,176.77,0.6769,0.0550,2023-06-30,2023-09-21,2033-09-21,E,True,True,False,True,False,False,0.1560,False,5,Data sopralluogo: 30/06/2023\nDoc impianto cli...,2,2,D,152.44,Compravendita in esecuzione immobiliare,0.0,0,L'unità immobiliare è stata valutata nello sta...,2003,T,Ancona,Trecastelli,1841,042050,D,0,0,1,7,9,1,0,60012,0.62,139.47,2.63,0.0,0.69,20.29,4.89,0.0,0.49,33.41,2.30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,173.49,13.07,34.41,88.11,Acca Software S.p.A.|TerMus|42.00|2023-09-21T1...,5.550000,41.630000,47.90,0.00,202.85,0.00,108.34,0.5341,0.0412,2023-09-15,2023-09-21,2033-09-21,G,True,False,False,True,False,False,0.2196,False,1,NaN,2,2,F,126.19,NaN,0.0,0,NaN,1880,T,ANCONA,FABRIANO,2198,042017,E,0,0,1,7,2,0,0,60044,0.74,119.28,0.00,1.0,NaN,NaN,NaN,NaN,0.29,54.21,13.07,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,177.51,126.49,41.87,144.68,DOCET,24.780000,90.220000,60.00,60.00,217.08,217.08,171.90,0.7918,0.0340,2023-09-21,2023-09-21,2033-09-21,D,True,True,False,True,False,False,0.5410,False,2,NaN,2,2,C,111.16,NaN,0.0,0,NaN,1964,s1,Ancona,Ancona,1688,042002,D,0,0,1,92,7,7,0,60125,0.63,117.54,112.05,0.0,1.17,19.69,4.74,0.0,0.35,40.28,9.70,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Missing values

In [7]:
# features with missing values
features_na = [features for features in df.columns if df[features].isnull().sum() > 1]

# feature name + percentage of missing values
for feature in features_na:
    print(feature, np.round(df[feature].isnull().mean(), 5), '% missing values')

informazioni_miglioramento 0.3349 % missing values
altra_motivazione 0.96559 % missing values
informazioni_aggiuntive 0.82869 % missing values
piano 0.01362 % missing values
provincia 0.00028 % missing values
servizio_1_efficienza 0.79097 % missing values
servizio_1_epnren 0.79097 % missing values
servizio_1_epren 0.79097 % missing values
servizio_1_simulato 0.79097 % missing values
servizio_2_efficienza 0.06385 % missing values
servizio_2_epnren 0.06385 % missing values
servizio_2_epren 0.06385 % missing values
servizio_2_simulato 0.06385 % missing values
servizio_3_efficienza 0.99696 % missing values
servizio_3_epnren 0.99696 % missing values
servizio_3_epren 0.99696 % missing values
servizio_3_simulato 0.99696 % missing values
servizio_4_efficienza 0.82087 % missing values
servizio_4_epnren 0.82087 % missing values
servizio_4_epren 0.82087 % missing values
servizio_4_simulato 0.82087 % missing values
servizio_5_efficienza 0.98123 % missing values
servizio_5_epnren 0.98123 % missing values
servizio_5_epren 0.98123 % missing values
servizio_5_simulato 0.98123 % missing values
servizio_6_efficienza 0.91324 % missing values
servizio_6_epnren 0.91324 % missing values
servizio_6_epren 0.91324 % missing values
servizio_6_simulato 0.91324 % missing values
servizio_7_efficienza 0.99512 % missing values
servizio_7_epnren 0.99512 % missing values
servizio_7_epren 0.99512 % missing values
servizio_7_simulato 0.99512 % missing values

### Relationship between missing values and the output (EPnren)

In [ ]:

for feature in features_na:
    data = df.copy()
    
    # 1 to indicate missing, 0 NOT missing
    data[feature] = np.where(data[feature].isnull(), 1, 0)
    
    # calculate the mean of the target for both groups
    data.groupby(feature)['epglnren'].median().plot.bar()
    plt.title(feature)
    plt.show()

## Numerical values

In [16]:
numerical_features = df.select_dtypes(include=['number']).columns.tolist()
print('Number of numerical features: ', len(numerical_features))

df[numerical_features].head()

Number of numerical features:  61

,epglnren,epglren,co2,ephnd,ephndlim,epglnrenrs,sup_riscaldata,sup_raffrescata,vol_riscaldato,vol_raffrescato,sup_disperdente,rapsv,asolsut,yie,motivazione,inverno,estate,epglnren_raggiungibile,energiaesportata,vetenergiaesportata,anno_costruzione,gradi_giorno,dpr412,destinazione_uso,oggetto_attestato,numero_unita,tipologia_edilizia,tipologia_costruttiva,proprieta_edificio,servizio_0_efficienza,servizio_0_epnren,servizio_0_epren,servizio_0_simulato,servizio_1_efficienza,servizio_1_epnren,servizio_1_epren,servizio_1_simulato,servizio_2_efficienza,servizio_2_epnren,servizio_2_epren,servizio_2_simulato,servizio_3_efficienza,servizio_3_epnren,servizio_3_epren,servizio_3_simulato,servizio_4_efficienza,servizio_4_epnren,servizio_4_epren,servizio_4_simulato,servizio_5_efficienza,servizio_5_epnren,servizio_5_epren,servizio_5_simulato,servizio_6_efficienza,servizio_6_epnren,servizio_6_epren,servizio_6_simulato,servizio_7_efficienza,servizio_7_epnren,servizio_7_epren,servizio_7_simulato
0,153.92,0.00,28.86,89.08,12.233700,49.060000,53.41,0.00,179.54,0.00,34.83,0.1940,0.0125,0.6025,1,2,1,120.10,0.0,0,1700,1899,0,0,1,12,3,0,0,0.73,121.56,0.00,1.0,NaN,NaN,NaN,NaN,0.57,32.36,0.00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,196.28,0.00,40.42,150.51,34.605655,68.612614,210.07,0.00,865.20,0.00,540.37,0.6246,0.0503,0.1794,1,2,2,77.96,0.0,0,1955,1888,0,0,1,1,0,0,0,0.83,181.88,0.00,0.0,NaN,NaN,NaN,NaN,0.84,14.40,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,193.17,9.82,39.06,88.74,21.663000,92.540000,72.29,72.29,261.13,261.13,176.77,0.6769,0.0550,0.1560,5,2,2,152.44,0.0,0,2003,1841,0,0,1,7,9,1,0,0.62,139.47,2.63,0.0,0.69,20.29,4.89,0.0,0.49,33.41,2.30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,173.49,13.07,34.41,88.11,5.550000,41.630000,47.90,0.00,202.85,0.00,108.34,0.5341,0.0412,0.2196,1,2,2,126.19,0.0,0,1880,2198,0,0,1,7,2,0,0,0.74,119.28,0.00,1.0,NaN,NaN,NaN,NaN,0.29,54.21,13.07,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,177.51,126.49,41.87,144.68,24.780000,90.220000,60.00,60.00,217.08,217.08,171.90,0.7918,0.0340,0.5410,2,2,2,111.16,0.0,0,1964,1688,0,0,1,92,7,7,0,0.63,117.54,112.05,0.0,1.17,19.69,4.74,0.0,0.35,40.28,9.70,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Temporal variables

In [21]:
time_features = [feature for feature in df if 'sopralluogo' in feature or 'validita' in feature]
time_features

['data_sopralluogo', 'inizio_validita', 'fine_validita']

In [22]:
# exploring the content of these features

for feature in time_features:
    print(feature, df[feature].unique())  # did not consider anno_costruzione because it is a numerical predictor, not a time feature

data_sopralluogo <StringArray>
['2023-09-11', '2023-09-13', '2023-06-30', '2023-09-15', '2023-09-21',
 '2021-05-14', '2023-09-05', '2023-09-22', '2023-09-12', '2023-09-19',
 ...
 '2023-08-27', '2023-08-20', '2020-11-04', '2022-10-07', '2022-01-19',
 '2022-10-01', '2020-08-24', '2020-10-27', '2020-09-10', '2021-09-14']
Length: 643, dtype: str
inizio_validita <StringArray>
['2023-09-21', '2023-09-22', '2023-10-10', '2023-12-18', '2023-10-13',
 '2023-09-23', '2023-09-24', '2023-09-25', '2023-11-10', '2023-09-26',
 ...
 '2023-09-11', '2023-09-12', '2023-09-13', '2023-09-14', '2023-09-15',
 '2023-09-16', '2023-09-17', '2023-09-18', '2023-09-19', '2023-09-20']
Length: 358, dtype: str
fine_validita <StringArray>
['2033-09-21', '2033-09-22', '2033-10-10', '2033-12-18', '2033-10-13',
 '2033-09-23', '2033-09-24', '2033-09-25', '2033-11-10', '2033-09-26',
 ...
 '2033-09-11', '2033-09-12', '2033-09-13', '2033-09-14', '2033-09-15',
 '2033-09-16', '2033-09-17', '2033-09-18', '2033-09-19', '2033-09-20']
Length: 358, dtype: str

### Is there any relation between anno_costruzione and epglnren?

In [ ]:
df.groupby('anno_costruzione')['epglnren'].median().plot.bar(figsize=(12, 6))
plt.xlabel('anno_costruzione')
plt.ylabel('Median epglnren')
plt.title('Median epglnren by anno_costruzione')
plt.xticks(rotation=70, ha='right', fontsize=5)
plt.tight_layout()
plt.show()

##### no further data exploration required for the temporal variables, since they have no relation to the prediction output

## Continuous and Discrete variables

In [42]:
discrete_features = [feature for feature in df if len(df[feature].unique()) < 5 and feature not in time_features]
print('Discrete features count: ', len(discrete_features))

Discrete features count:  29

In [43]:
discrete_features

['presenza_clim_invernale',
 'presenza_clim_estiva',
 'presenza_vent_meccanica',
 'presenza_produzione_acs',
 'presenza_illuminazione',
 'presenza_trasporto_pc',
 'nzeb',
 'inverno',
 'estate',
 'vetenergiaesportata',
 'zona_climatica',
 'destinazione_uso',
 'oggetto_attestato',
 'proprieta_edificio',
 'servizio_0_simulato',
 'servizio_1_simulato',
 'servizio_2_simulato',
 'servizio_3_efficienza',
 'servizio_3_epnren',
 'servizio_3_epren',
 'servizio_3_simulato',
 'servizio_4_efficienza',
 'servizio_4_epnren',
 'servizio_4_epren',
 'servizio_4_simulato',
 'servizio_5_efficienza',
 'servizio_5_simulato',
 'servizio_6_simulato',
 'servizio_7_simulato']