In [5]:
import pandas as pd

csv_file = "../data/raw/ape_marche_dataset.csv"

df_1= pd.read_csv(csv_file)

df_1 = df_1.drop(columns='oggetto_attestato')
df_1 = df_1.drop(columns='file_timestamp')

df_1

,scadenza,uso_edificio,num_unita,zona_climatica,anno_costruzione,superficie_riscaldata,superficie_raffrescata,vol_lordo_riscaldato,vol_lordo_raffrescato,climatizzazioneInvernale,...,tipologia_edilizia,tipologia_costruttiva,ephnd_limit,ep_standard,u_opaco_medio,superficie_opaca_tot,u_vetrato_medio,superficie_vetrata_tot,ricambi_aria_ora,xml_filename
0,2035-03-18,0,1,E,1900,110.24,0.0,381.21,0.00,1,...,3,0,25.50,62.78,1.7972,126.70,4.9,19.60,0.3,4vicolodel piano.xml
1,2035-06-18,0,1,D,1940,138.09,0.0,592.78,0.00,1,...,3,0,22.10,54.70,1.2921,143.37,2.3,11.76,0.3,AN_Via Trieste6.xml
2,2035-07-31,0,1,D,1963,79.45,0.0,296.44,0.00,1,...,2,1,34.11,74.71,1.4957,155.93,2.9,14.21,0.3,An_ViaCorinaldo5.xml
3,2033-03-03,0,8,D,1958,85.44,0.0,318.79,0.00,1,...,2,7,32.80,81.15,1.5059,174.64,3.7,12.74,0.3,APE Angelani Rosalba.xml
4,2034-03-14,0,1,D,1935,89.00,89.0,439.69,439.69,1,...,1,0,69.09,125.97,1.3809,302.51,2.9,16.66,0.3,Ape Antinori Daniela.xml
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,2035-02-04,0,1,D,2002,50.10,50.1,179.22,179.22,1,...,2,7,23.29,74.91,1.1887,85.88,2.3,8.82,0.3,Via_Italia19.xml
300,2035-01-23,0,1,D,1965,64.00,64.0,238.79,238.79,1,...,2,7,19.02,66.65,1.1425,66.09,2.9,8.82,0.3,Via_Metauro27_Senigallia.xml
301,2034-07-16,0,1,D,1990,87.90,87.9,298.14,298.14,1,...,2,7,24.28,67.74,1.3838,131.57,2.9,10.78,0.3,VIA_Sparapani_AN.xml
302,2035-10-20,0,1,D,1950,49.17,0.0,193.48,0.00,1,...,2,9,34.34,79.66,1.3472,115.31,2.9,7.84,0.3,VicolodelPesco1.xml
303,2034-12-20,0,1,D,1900,58.13,0.0,192.84,0.00,1,...,3,0,25.97,67.42,1.0758,101.56,4.9,7.84,0.3,VicoloFiorenzuola6.xml

In [6]:
json_file = '../data/raw/AN2023.json'

df_2 = pd.read_json(json_file)

df_2

,epglnren,epglren,co2,ephnd,software_utilizzato,ephndlim,epglnrenrs,sup_riscaldata,sup_raffrescata,vol_riscaldato,...,zona_climatica,dpr412,destinazione_uso,oggetto_attestato,numero_unita,tipologia_edilizia,tipologia_costruttiva,proprieta_edificio,cap,servizi
0,153.92,0.00,28.86,89.08,Namirial Termo 6,12.233700,49.060000,53.41,0.00,179.54,...,D,0,0,1,12,3,0,0,60035,"[{'servizio_energetico': 0, 'tipo_impianto': N..."
1,196.28,0.00,40.42,150.51,TERMOLOG EpiX,34.605655,68.612614,210.07,0.00,865.20,...,D,0,0,1,1,0,0,0,60015,"[{'servizio_energetico': 0, 'tipo_impianto': 1..."
2,193.17,9.82,39.06,88.74,Namirial Termo 6,21.663000,92.540000,72.29,72.29,261.13,...,D,0,0,1,7,9,1,0,60012,"[{'servizio_energetico': 0, 'tipo_impianto': 0..."
3,173.49,13.07,34.41,88.11,Acca Software S.p.A.|TerMus|42.00|2023-09-21T1...,5.550000,41.630000,47.90,0.00,202.85,...,E,0,0,1,7,2,0,0,60044,"[{'servizio_energetico': 0, 'tipo_impianto': N..."
4,177.51,126.49,41.87,144.68,DOCET,24.780000,90.220000,60.00,60.00,217.08,...,D,0,0,1,92,7,7,0,60125,"[{'servizio_energetico': 0, 'tipo_impianto': 4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10864,144.34,1.09,28.94,71.72,Edilclima S.r.l.|EC 700 calcolo prestazioni en...,43.407486,87.025519,33.66,33.66,140.00,...,D,0,0,1,3,3,0,0,60019,"[{'servizio_energetico': 0, 'tipo_impianto': 0..."
10865,75.19,40.10,16.68,17.47,Namirial Termo 5,0.000000,73.710000,42.49,42.49,148.90,...,D,0,0,1,9,4,1,0,60131,"[{'servizio_energetico': 0, 'tipo_impianto': 5..."
10866,75.58,7.48,15.25,12.23,Acca Software S.p.A.|TerMus|42.00|2023-09-21T1...,-1.000000,63.990000,195.45,0.00,1031.94,...,D,4,1,1,23,2,1,1,60035,"[{'servizio_energetico': 0, 'tipo_impianto': 0..."
10867,450.58,1.56,88.86,261.60,Namirial Termo 5,21.139400,60.860000,68.96,0.00,259.63,...,E,0,0,1,2,1,0,0,60030,"[{'servizio_energetico': 0, 'tipo_impianto': 0..."
10868,155.69,112.86,34.51,113.09,Namirial Termo 5,19.152600,74.200000,61.07,61.07,281.00,...,D,0,0,1,9,4,1,0,60131,"[{'servizio_energetico': 0, 'tipo_impianto': 5..."